package com.excellence.springbootcrudapisecurity;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;

import com.excellence.springbootcrudapisecurity.service.EmailSenderService;

@SpringBootApplication
public class SpringBootCrudApiSecurityApplication {

	@Autowired
	private EmailSenderService senderService;
	
	public static void main(String[] args) {
		SpringApplication.run(SpringBootCrudApiSecurityApplication.class, args);
	}
	
	@EventListener(ApplicationReadyEvent.class)
	public void sendMail()
	{
		senderService.sendEmail("manish20k99@gmail.com", "This email confirmation purpose only left 2 hours"
				+ " complete your project hurry up!"
				, "This is email confirmation purpose generated by excellence technology");
	}
	

}
